name: Frontend Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Changement de Node 18 à 14

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run tests and generate reports
        working-directory: front
        run: |
          npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
          # Affiche les fichiers générés dans coverage/bobapp
          echo "=== Contenu de coverage/bobapp ==="
          ls -R coverage/bobapp
          # Affiche le contenu de lcov.info si présent
          if [ -f "coverage/bobapp/lcov.info" ]; then 
            echo "✅ lcov.info trouvé ! Voici son contenu :"; 
            cat coverage/bobapp/lcov.info;
          else 
            echo "❌ lcov.info NON trouvé !"; 
          fi

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-report
          path: front/coverage


