name: SonarCloud Analysis

on:
  workflow_dispatch:

jobs:
  sonarcloud-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-backend

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Set up Java for Backend Analysis
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Backend & Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
          -Dsonar.projectKey=Malck_P10_Fullstack_BobApp \
          -Dsonar.organization=malck \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  sonarcloud-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Frontend Dependencies
        run: |
          cd front
          npm ci

      - name: Run Tests and Generate Coverage Report
        run: |
          echo "Début des tests Angular"
          cd front
          # Ignore les erreurs non critiques pendant les tests
          npm test -- --code-coverage --browsers=ChromeHeadless --watch=false || true
          echo "Tests Angular terminés"
          echo "=== Contenu de coverage ==="
          ls -R coverage

      - name: Run SonarCloud for Frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd front
          npx sonar-scanner -Dsonar.projectKey=Malck_P10_Fullstack_BobApp \
          -Dsonar.organization=malck \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=src \
          -Dsonar.exclusions=node_modules/**,dist/** \
          -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info
