name: SonarCloud Analysis

on:
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Frontend Dependencies & Run Tests
        working-directory: ./front
        run: |
          npm ci
          npm test -- --code-coverage --browsers=ChromeHeadless --watch=false
        env:
          CI: true  # Permet à Angular CLI de fonctionner en mode CI

      - name: Move lcov.info to Backend Folder
        run: |
          mv front/coverage/bobapp/lcov.info back/coverage/lcov.info

      - name: Set up Java for Backend Analysis
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=Malck_P10_Fullstack_BobApp \
          -Dsonar.organization=malck \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
