name: SonarCloud Analysis

on:
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Cacher les packages Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      # Installer Java pour l'analyse backend
      - name: Set up Java for Backend Analysis
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Analyse backend avec Maven + Envoi de rapport Jacoco
      - name: Build Backend & Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=Malck_P10_Fullstack_BobApp \
          -Dsonar.organization=malck \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      # Installer les dépendances frontend
      - name: Install Frontend Dependencies
        run: |
          cd front
          npm install

      # Lancer les tests Angular et générer la couverture
      - name: Run Angular Tests
        run: |
          cd front
          npm test -- --code-coverage --browsers=ChromeHeadless --watch=false || true
          echo "=== Listing coverage folder ==="
          ls -R coverage

      # Vérifier l'existence de lcov.info
      - name: Check if lcov.info exists
        run: |
          if [ ! -f front/coverage/bobapp/lcov.info ]; then 
            echo "Fichier lcov.info non trouvé, vérifie les tests !"; 
            exit 1; 
          else 
            echo "Fichier lcov.info trouvé !"; 
            cat front/coverage/bobapp/lcov.info
          fi

      # Fusionner les rapports de couverture et les envoyer à SonarCloud
      - name: Run SonarCloud Analysis (Frontend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd front
          npx sonar-scanner \
            -Dsonar.projectKey=Malck_P10_Fullstack_BobApp \
            -Dsonar.organization=malck \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=src \
            -Dsonar.exclusions=node_modules/**,dist/** \
            -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info


